<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-E3E6SI5" failures="2" tests="4" name="Test" time="9.636" errors="0" timestamp="2025-08-03T11:28:11 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.928"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.526">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUserByName(UserTests2.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.953">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testUpdateUserByName(UserTests2.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.467"/>
</testsuite> <!-- Test -->
